<?php
/**
 * @date   2015-08-24
 * @desc   新增 客戶身份證字號 與 說明
 * @author Shawn Chang
 */
//$language['_payING_024']
$language = array(

	'_payING_001' => "Credit Card Payment - Your Ticket Booking Record",
	'_payING_002' => "Outbound Ticket Booking Record",
	'_payING_003' => "Outbound Booking code",
	'_payING_004' => "Train Number",
	'_payING_005' => "Train Type",
	'_payING_006' => "DEP Time:",
	'_payING_007' => "Check your reserved date again!",
	'_payING_008' => "Departure Station",
	'_payING_009' => "Destination Station",
	'_payING_010' => "Outbound tickets",
	'_payING_011' => "",	//張
	'_payING_012' => "Adult ticket",
	'_payING_013' => "Child ticket",
	'_payING_014' => "Senior ticket",
	'_payING_015' => "Terms of Using Tickets",
	'_payING_016' => "Return bround Ticket Booking Record",
	'_payING_017' => "Return bround Booking code",
	'_payING_018' => "Return bround tickets",
	'_payING_019' => "Confirm",
	'_payING_020' => "Restart",
	'_payING_021' => '1.<span style="color:#00F; background-color:#DAEEF3;">Only senior(over 65 ages) Republic of China citizen and Foreign senior who is eligible for Mackay Project can pay senior fare.<br>Foreign senior should pay adult fare.</span><br>2. You can change the number of tickets based on the ticket booking records. <span style="color:#F00;">Online payment for tickets can be made once. Unpaid tickets will not be reserved.</span><br>3. After 5 minutes of inactivity, the system will automatically log out.<br>4. If the Internet connection is lost or the ticketing system is out of order during credit card payment processing, <span style="font-weight:bold; color:#F00;">you can use "Payment Records Query" to check if your transaction was successful.</span>',
	'_payING_022' => "Disabled ticket",
	'_payING_023' => "Your Ticket Booking Record",
	'_payING_024' => "Credit Card Payment",
	'_payING_025' => "TAROKO",
	'_payING_026' => "Your Ticket Booking Record",
	'_payING_027' => "Price per ticket",
	'_payING_028' => "Total",
	'_payING_029' => "dollars",
	'_payING_030' => "NT$",
	'_payING_031' => "Credit card authorization amount",
	'_payING_032' => "Enter the following credit card data",
	'_payING_033' => 'The system uses the latest (3D Verification) security mechanism. At the early stage, it is only available for VISA and Mastercard.',
	'_payING_034' => "Credit card number",
	'_payING_035' => "The last three digits of the security <br />code on the back",
	'_payING_036' => "Help",
	'_payING_037' => "Vaild thru",
	'_payING_038' => "month",
	'_payING_039' => "year",
	'_payING_040' => "Apply for a subsidy using the National Travel Card",
	'_payING_041' => "Yes, destination",
	'_payING_042' => "From",
	'_payING_043' => "To",
	'_payING_044' => "民國",
	'_payING_045' => "day",
	'_payING_046' => "No",
	'_payING_047' => "* After payment, you can use <br />(Payment Records Query) to make <br />sure your payment was successful.",
	'_payING_047-1' => "Please confirm the information again.<br>If you get an <font color=red>Authorization Failed</font> message, please ask the card-issuing bank for assistance.",
	'_payING_048' => "Confirm payment",
	'_payING_049' => "This website uses advanced 128-bit SSL encryption to provide comprehensive security to ensure your data will not be stolen during data transmission.",
	'_payING_050' => "Civil servants who pay using their National Travel Card by applying for “Compulsory Vacation Subsidies”must always click (Yes) and select the destination on this payment webpage to send their data to NCCC's Verification Sytem.",
	'_payING_051' => "Credit card authorization failed",
	'_payING_052' => "Sorry, your credit card authorization has failed.",
	'_payING_053' => "Authorization failure reason",
	'_payING_054' => "Fill it in again. Make sure the credit card data you completed is correct, and try again",
	'_payING_055' => "Successful Credit Card Payment",
	'_payING_056' => "Thank you! Your credit card payment authorization has been granted successfully!<br>The following is your payment data!",
	'_payING_057' => "Yes",
	'_payING_058' => "Number",
	'_payING_059' => "Seat Number",
	'_payING_060' => "Credit Card Data",
	'_payING_061' => "Authorization time",
	'_payING_062' => "Authorization code",
	'_payING_063' => "Print this page",
	'_payING_064' => "Whether the National Travel Card",
	'_payING_065' => "Tourist spots",
	'_payING_066' => "Print the Ticket Pick-Up Form for credit card payment",
	'_payING_067' => "Complete ticket purchase by credit card",
	'_payING_068' => '1. After the credit card payment, take your ID card (or passport or residence permit if you are overseas Chinese or foreigner) at the “Ticket Counters” 、post office and convenience store (7-ELEVEN、 Hi-Life、 Family Mart、 OK Mart) <span style="color:#F00">30 minutes before taking the train</span>.<br>2. <span style="color:#F00">One booking code can charge only one fee, sometimes credit card issue bank will inform coustomer "Authorization code" when you try to pay, either it is successful or not. You can use (Payment Records Query) to check if your transaction was successful.</span><br>3. To cancel your credit card payment, complete the payment cancellation process on the website 30 minutes before the train departs.<br>4. All tickets with the same Booking code should be cancelled together when you cancel your credit card payment. To cancel partial payment, go to the station to pick up your tickets and refund them using the original credit card you used to pay.<br>5. A handling fee will be charged for each ticket that is cancelled.',
	'_payING_069' => "Credit Card Payment for Ticket Purchase - Records Query",
	'_payING_070' => '<span style="color:#F00;">If the internet connection is lost or the ticketing system is out of order during credit card payment processing, you can use (Payment Records Query) to check if your transaction was successful.</span>',
	'_payING_071' => 'After the credit card payment, take your ID card (which is used to book) and Booking code at the ticket counter 30 minutes before taking the train.',
	'_payING_072' => 'To cancel your credit card payment, complete the payment cancellation process on the website <span style="color:#F00;">30 minutes</span> before the train departs.',
	'_payING_072-1' => 'To cancel your credit card payment, complete the payment cancellation process on the website <span style="color:#F00;">30 minutes before the train departs.</span>',
	'_payING_072-2' => 'To cancel your credit card payment, complete the payment cancellation process on the website 30 minutes before the train departs.',
	'_payING_073' => 'All tickets with the same Booking code should be cancelled together when you cancel your credit card payment. To cancel partial payment, go to the station to pick up your tickets and refund them using <span style="color:#F00;">the original credit card you used to pay.</span>',
	'_payING_073-1' => 'All tickets with the same Booking code should be cancelled together when you cancel your credit card payment. To cancel partial payment, go to the station to pick up your tickets and refund them using <span style="color:#F00;">the original credit card</span> you used to pay.',
	'_payING_073-2' => 'All tickets with the same Booking code should be cancelled together when you cancel your credit card payment. To cancel partial payment, go to the station to pick up your tickets and refund them using the original credit card you used to pay.',
	'_payING_074' => 'A handling fee will be charged for each ticket that is cancelled.',
	'_payING_075' => "Your credit card payment data",
	'_payING_076' => "Your authorization records as shown below",
	'_payING_077' => "Authorization time",
	'_payING_078' => "Authorization amount",
	'_payING_079' => "The following shows the cancellation record for this transaction payment.",
	'_payING_080' => "The handling fee for ticket refund amounts to",
	'_payING_081' => "The time at which your credit card payment was cancelled",
	'_payING_082' => "Total refund amount",
	'_payING_083' => 'After the credit card payment, take your <span style="color:#F00;">ID card (which is used to book) and Booking code</span> to collect your tickets at TRA ticket counter 30 minutes before taking the train.',
	'_payING_084' => '<span style="color:#F00;">You can use (Payment Records Query) to check if your transaction was successful.</span>',
	'_payING_085' => "Payment records query complete",
	'_payING_086' => "Cancellation of Credit Card Payment for Ticket Purchase",
	'_payING_087' => "If you cancel the payment, the Booking code will be returned to the ticket booking system for other passengers to book.",
	'_payING_088' => "Login to cancel payment",
	'_payING_089' => "-Price per ticket",
	'_payING_090' => "one-tenth of the ticket price will be charged for the holiday ticket",
	'_payING_091' => "Refunding Fee",
	'_payING_092' => "total",
	'_payING_093' => "Price per ticket NT$:13 dollars",
	'_payING_094' => 'A handling fee will be charged per cancellation:',
	'_payING_095' => "I confirm cancellation of the credit card payment for ticket purchase",
	'_payING_096' => "Press this button to complete the refund process. Save your page data after the refund process is completed.",
	'_payING_097' => "Your seat will be unreserved once the cancellation of the online credit card payment is confirmed.",
	'_payING_098' => '<span style="color:#F00;">You can use (Payment Records Query) to check your cancellation records.</span>',
	'_payING_099' => "Thank you! The cancellation process is completed.",
	'_payING_100' => "Total refund amount: NT$ ",
	'_payING_101' => "The refund amount will be transferred to your credit card account within 3~5 business days. We welcome you to take the trains of Taiwan Railways again.",
	'_payING_102' => "Your original ticket booking date",
	'_payING_103' => "Complete the cancellation of credit card payment",
	'_payING_104' => "Print the payment cancellation data",
	'_payING_105' => "(except train No.684,685,781,782)",
	'_payING_106' => "Passengers will enjoy discounts for booking the train number 684、685 and 781、782 from Taipei Train Station to Hualien Train Station to Taitung Train Station or Kaohsiung Train Station to Taitung Train Station.",
	'_payING_107' => "ID/ Passport No.",
	'_payING_108' => "ticket type",
	'_payING_109' => "Time to pick up",
	'_payING_110' => "ID No. used for booking",
	'_payING_111' => "Signature",
	'_payING_112' => 'To save your time and protect the rights of the individuals who booked their tickets and the individuals who paid for the tickets, print this form and fill in your ID card number and Booking code. <span style="color:#F00;">Take your ID card</span> (or password if you are overseas Chinese or foreigner) and submit the Ticket pick up form to the <span style="color:#F00;">TRA station ticket counter</span> to pick up your tickets up to <span style="color:#F00;">30 minutes before the train departs.</span>',
	'_payING_113' => 'Do not confuse your ID number with your Booking code. It is recommended to print the (Ticket Pick-up Form) after payment, or complete the form based on the information shown on the (Ticket Pick-up Form) page.',
	'_payING_114' => 'To cancel some of your tickets, go to the station to pick up your tickets and refund some of them using the original credit card you used to pay.',
	'_payING_115' => 'If you forget to bring your completed Ticket Pick-up Form, keep your (ID number) and Booking code in mind and complete the blank form at the station to pick up your tickets.',
	'_payING_116' => 'Can not find the booking record. Please confirm the ID for booking tickets.',
	'_payING_117' => '<span style="color:#F00; font-weight:bold;">This form cannot be used as ticket. Please take your ticket to take the train.<br>Passengers without tickets must pay the ticket fare.<br>Without any justified reason,charge extra 50% penalty.</span>',
	'_payING_118' => "The content of this webpage can't be used as certification. Please take the train by the ticket.",
	'_payING_119' => "Class",
	'_payING_120' => "Business class seats",
	'_payING_122' => "Take your ID card (or passport or residence permit if you are overseas Chinese or foreigner) at the “Ticket Counters” 、post office and convenience store (7-ELEVEN、 Hi-Life、 Family Mart、 OK Mart) <span style=\"color:#F00\">30 minutes before taking the train</span>.",
    '_payING_123' => '<span style="color:#F00; font-weight:bold;">This page cannot be used as ticket.<br>Please take your ticket to take the train.<br>Passengers without tickets must pay the ticket fare.<br>Without any justified reason,charge extra 50% penalty.</span>',
    '_payING_124' => '',
	'_payING_125' => '',
	'_payING_127' => '<span style="color:#F00;">Refund and ticket change must be made at the TRA stations with the original credit card used to pay.</span>',
    '_payING_128' => '<span style="font-weight:bold;">Inquire Booking Records webpage：<a href ="http://railway.hinet.net/net_eng.htm">http://railway.hinet.net/net_eng.htm</a></span>',
    '_payING_129' => '<span style="font-weight:bold;">Payment Records Query webpage：<a href ="https://ticket.ctbcbank.com/railway/index.php">https://ticket.ctbcbank.com/railway/index.php</a></span>',
    '_payING_130' => '<span style="color:#00F; background-color:#DAEEF3; font-weight:bold;">Refund and ticket change must be made at the TRA stations with the original credit card used to pay.</span>',
    '_payING_131' => 'Non-vegetarian',
    '_payING_132' => 'Vegetarian',
    '_payING_133' => '',# 個
    '_payING_134' => 'Non-vegetarian: %s ',
    '_payING_135' => 'Vegetarian: %s ',
    '_payING_136' => '[%s] %s: %s-Price per bento: %s dollars',
    '_payING_137' => 'To choose the number of bento again',
    '_payING_138' => '',// 颱風退票之旅客，須至本局車站售票窗口辦理全額退票，方可免收退票手續費。 如於本系統取消付款仍須收取手續費。
	
	'_payCITY_001' => "Taipei City",
	'_payCITY_002' => "Keelung City",
	'_payCITY_003' => "New Taipei City",
	'_payCITY_004' => "Yilan County",
	'_payCITY_005' => "Hsinchu City",
	'_payCITY_006' => "Hsinchu County",
	'_payCITY_007' => "Taoyuan County",
	'_payCITY_008' => "Miaoli County",
	'_payCITY_009' => "Taichung City",
	'_payCITY_010' => "Changhua County",
	'_payCITY_011' => "Nantou County",
	'_payCITY_012' => "Chiayi City",
	'_payCITY_013' => "Chiayi County",
	'_payCITY_014' => "Yunlin County",
	'_payCITY_015' => "Tainan City",
	'_payCITY_016' => "Kaohsiung City",
	'_payCITY_017' => "Pingtung County",
	'_payCITY_018' => "Taitung County",
	'_payCITY_019' => "Hualien County",
	'_payCITY_020' => "Penghu County",
	'_payCITY_021' => "Kinmen County",
	'_payCITY_022' => "Lienchiang County",
	'_payCITY_023' => "Nanhai Islands",
	'_payCITY_024' => "Diaoyutai Archipelago",

	'_payPHP_001' => "Credit Card Payment for Ticket Purchase",
	'_payPHP_002' => "An error message indicating a wrong seat number may appear if you make the payment in the payment system right after booking a ticket. In most cases, this is because Chunghwa Telecom's ticket booking system does not send the booking information to Taiwan Railway's ticketing system immediately, which in turn makes the payment system unable to receive the required information. Please make the payment 2 hours later.",
	'_payPHP_003' => "One-way ticket",
	'_payPHP_004' => "Check if you are a foreigner (Fill in your Passport or Residence permit or Entry-and-exit-permits number.)",
	'_payPHP_005' => "Booking code",
	'_payPHP_006' => "ID No.",
	'_payPHP_007' => 'If you cannot book all of your round-trip tickets at the same time, you can pay for the one-way tickets (the departure and destination stations for the outbound and Return bround trips should be the same).',
	'_payPHP_008' => "Round-trip ticket",
	'_payPHP_009' => 'Outbound',
	'_payPHP_010' => "Return bround",
	'_payPHP_011' => "Click here if the same as above",
	'_payPHP_012' => "Submit",
	'_payPHP_013' => "Cancel",
	'_payPHP_014' => "Description:",
	'_payPHP_015' => "The departure and destination stations for the outbound and Return bround trips should be the same. If the distance between them is less than 80 kilometers, you should go there and back on the same day. <a href='http://www.railway.gov.tw/tw/CP.aspx?sn=3611&n=6832' target='_blank'>Check operating mileage.</a>",
	'_payPHP_016' => "The round-trip ticket allows different train types.",
	'_payPHP_017' => "The round-trip ticket allows one ID number with two Booking codes, or two ID numbers with two Booking codes.",
	'_payPHP_018' => "If the Internet connection is lost or the ticketing system is out of order during credit card payment processing, <font style=\"font-weight: bold; color:#FF0000;\">you can use (Payment Records Query) to check if your transaction was successful.</font>",
	'_payPHP_019' => "",
	'_payPHP_020' => "<font style=\"color:#FF0000; background-color:#DAEEF3;\">By January 26,2016,the 10% round-trip<br>ticket discount and the 5% online payment<br>discount will be cancelled.</font>",
	'_payPHP_021' => '', // 一般公告

	'_Alert_txt_001' => 'Your One-way/Round-trip ticket is not selected!',
	'_Alert_txt_002' => 'Your ID No. has not been entered yet!',
	'_Alert_txt_003' => 'Your ID No. is too short or too long!',
	'_Alert_txt_004' => 'The prefix of your ID No. must be a capital letter!',
	'_Alert_txt_005' => 'The last two digits of your ID No. are wrong!',
	'_Alert_txt_006' => 'The last nine characters of your ID No. should be digits.',
	'_Alert_txt_007' => 'Your ID No. is wrong!',
	'_Alert_txt_008' => 'The password number should consist of alphanumeric characters only, without any special symbols!',
	'_Alert_txt_009' => 'Your Booking code has not been entered yet!',
	'_Alert_txt_010' => 'The Booking code is too short or too long.',
	'_Alert_txt_011' => 'The Booking code should be consist of numbers only.',
	'_Alert_txt_012' => 'The Booking codes for the outbound and Return bround trips cannot be identical!',
	'_Alert_txt_013' => 'The refund handling fee is greater than the transaction amount. Refund failed! Go to the counter to refund your ticket!',
	'_Alert_txt_014' => "Authorization is granted but the data matching on the Taiwan Railways host has failed. Try again!",
	'_Alert_txt_015' => "Data delivery on the Taiwan Railways host has failed! Login again! Possible causes:",
	'_Alert_txt_016' => '',
	'_Alert_txt_017' => 'The number of outbound tickets is wrong! Fill in an appropriate number of tickets!',
	'_Alert_txt_018' => 'The number of return bround tickets is wrong! Fill in an appropriate number of tickets!',
	'_Alert_txt_019' => 'Make sure the number of tickets purchased is correct.',
	'_Alert_txt_020' => 'Ticket price data exchange has failed! Try again!',
	'_Alert_txt_021' => 'The expenditure summary has not been entered yet!',
	'_Alert_txt_022' => 'The credit card number has not been entered yet!',
	'_Alert_txt_023' => 'The card number entered is incomplete!',
	'_Alert_txt_024' => 'The credit card number you entered is not a VISA or Mastercard!',
	'_Alert_txt_025' => 'Card number incorrect! Its format is incorrect.',
	'_Alert_txt_026' => 'Data access error!! Close all browser windows! Try again!',
	'_Alert_txt_027' => 'Login failed! Login again! Possible causes:',
	'_Alert_txt_028' => 'Among the transactions that can be cancelled, the payment records for your transaction cannot be found. Make sure the data you entered has not expired. Requery!',
	'_Alert_txt_029' => 'Refund time exceeded! Ticket refunding should be done 30 minutes before the train departs.',
	'_Alert_txt_030' => 'Login failed! Login again! Possible cause: You entered an incorrect account password.',
	'_Alert_txt_031' => 'You are on the system blacklist. You cannot make a payment using this system!',
	'_Alert_txt_032' => 'Your credit card payment records cannot be found. Try again',
	'_Alert_txt_033' => 'Check (I accept) to proceed with payment. Otherwise, make the payment in other manners. Check “No” if you do want to buy a ticket.',
	'_Alert_txt_034' => 'The last three digits of the security code on the back of the card should be numbers.',
	'_Alert_txt_035' => 'The last three digits of the security code on the back of the card has not been entered yet!',
	'_Alert_txt_036' => 'The credit card has expired.',
	'_Alert_txt_037' => 'The amount has not been entered yet!',
	'_Alert_txt_038' => 'The amount format entered is incorrect!',
	'_Alert_txt_039' => 'No credit card payment records can be found. Check the data entered and requery it.',
	'_Alert_txt_040' => 'Is busy, please try again later!',
    '_Alert_txt_041' => 'The number of outbound bento more then the ticket! Please use the link [Choose the number of bento] to choose the number of bento again.',
    '_Alert_txt_042' => 'The number of return bound bento more then the ticket! Please use the link [Choose the number of bento] to choose the number of bento again.',
    '_Alert_txt_043' => '無法組成去回票，去回程票種(成人票,孩童票,敬老票,愛心票)與張數需相同!',

	'_M001_L' => "Problems with the ticket booking system.",
	'_M001_M' => '<a href="http://www.railway.gov.tw/tw/CP.aspx?sn=966&n=1335" target="_blank">Instructions</a> of Telephone Booking <br><br>Problems with the Internet ticketing or telephone booking system <br>Hotline: 0800-080-412<br>',
	'_M001_Mn' => 'Query the hotline number',
	'_M002_L' => "Online Payment System Problems",
	'_M002_M' => '<a href="http://www.railway.gov.tw/tw/CP.aspx?sn=7447" target="_blank">Instructions</a> of the Online Credit Card Payment for Ticket Purchase System<br><br>Problems with the Online Credit Card Payment System <br>Hotline: (02)2769-9031<br>',
	'_M003_L' => "Tickets and Train Problems",
	'_M003_M' => 'Contact each station for problems with ticket and train information. <a href="http://www.railway.gov.tw/tw/CP.aspx?sn=3606&n=6829" target="_blank">Query </a>the hotline number of each station. <br><br><a href="http://www.railway.gov.tw/tw/CP.aspx?sn=7447&n=1333" target="_blank">Query </a>the operating services of Taiwan Railways <br><br><a href="http://www.railway.gov.tw/tw/faq.aspx?n=6882" target="_blank">FAQs</a> for each service offered by Taiwan Railways<br>',
	'_M003_M2' => 'Contact each station for problems with ticket and train information.',
	'_M003_M3' => 'Query the hotline number of each station.',
	'_M004_L' => "Ticket Pick-up Form",
	'_M004_M' => 'If you do not have a printer to print a "Ticket Pick-up Form," you could take your identification card as well as Booking code and complete the form at the ticket window or information desk 30 minutes before taking the train. <br><br><a href="get_train.htm" target="_blank">Print a Ticket Pick-up Form</a><br><br>It is recommended to use "Payment Records Query" to print the “Ticket Pick-up Form” on the payment records query page. (The system automatically searches for the data of the individual who booked the ticket, including the ID number, Booking code, and departure and destination stations.)<br>',
	'_TW_Railways' => "Taiwan Railways",
	'_Service_Query' => 'Query the hotline number',
	'_M001_TEL' => "TEL:",

	'_Top_pop_gif' => "top_pop_en.gif",
	'_Top_pop_gif_24h' => "top_pop_en_24h.gif",
	'_IE_only_gif' => "ie_only_en.gif",
	'_payment_18a_jpg' => "payment_18a_en.jpg",
	'_payment_18b_jpg' => "payment_18b_en.jpg",
	'_payment_18a_no_jpg' => "payment_18a_no_en.jpg",
	'_payment_19a_jpg' => "payment_19a_en.jpg",
	'_payment_19b_jpg' => "payment_19b_en.jpg",
	'_payment_20a_jpg' => "payment_20a_en.jpg",
	'_payment_20b_jpg' => "payment_20b_en.jpg",
	'_payment_20a_no_jpg' => "payment_20a_no_en.jpg",
	'_payment_21a_jpg' => "payment_21a_en.jpg",
	'_payment_21b_jpg' => "payment_21b_en.jpg",
	'_payment_22a_jpg' => "payment_22a_en.jpg",
	'_payment_22b_jpg' => "payment_22b_en.jpg",
	'_payment_23a_jpg' => "payment_23a_en.jpg",
	'_payment_23b_jpg' => "payment_23b_en.jpg",
	
	'_Other_Link' => "Relevant links:",
	'_System_Builder' => "Built by:",
	'_Green_World' => "allPay Third-Party Payment Co., Ltd.",
	'_China_Trust' => "Chinatrust Commercial Bank.",
	'_Taiwan_Railways' => "Homepage of Taiwan Railways",
	
	'_Dear_passenger' => "Dear passenger",
	'_Important' => "Important",
	'_Important_01' => "An error message indicating a wrong seat number may appear if you make the payment in the payment system right after booking a ticket. In most cases, this is because Chunghuwa Telecom's ticket booking system does not immediately send the booking information to Taiwan Railway's ticketing system, which in turn makes the payment system unable to receive the required information. Please make the payment 2 hours later.",
	'_Important_02' => "Passengers who make a payment via a digital credit card (virtual one) cannot refund their tickets. Do not use them where possible.<br><br>",
	'_CloseBT' => "Close",
	'_page01_001' => "To protect your rights, read the rules below carefully. If the individual (buyer) who books a ticket is not the individual (passenger) who will take the train, he/she will be deemed as an agent and have the obligations to advise the passenger of the rules and restrictions.",
	'_page01_002' => "Check the box for your acknowledge of terms and condition. <br>I have read the ticketing rules below thoroughly and accept all of them.",
	'_page01_003' => "(You must click “here” before you can proceed with ticketing. Otherwise, you must buy your ticket in other ways.)",
	'_page01_004' => "Start buying a ticket",
	'_page01_005' => "The rules of “Online Credit Card Payment for Ticket Purchase” for Taiwan Railways Administration",
	'_page01_006' => "<span style=\"color:#00F; background-color:#DAEEF3;\">Refund and ticket change must be made at the TRA stations<br>with the original credit card used to pay.</span><br><span style=\"color:#F00; background-color:#DAEEF3;\">You can use “Payment Records Query” for inquiring the record of credit card payment<br>and print the Ticket Pick Up Form.</span><br><span style=\"color:#31859C;\">By January 26, 2016,the 10% round-trip ticket discount and the 5% online payment discount will be cancelled.</span>",
	'_page01_007' => 'Always take note of your <span style="color: #F00;">Booking code</span> and your <span style="color: #F00;">Passport number</span> (which is used to book). You may not pick up your ticket if the completed ticket type information is incorrect.<br><span style="color:#00F; background-color:#DAEEF3;">Only senior(over 65 ages) Republic of China citizen and Foreign senior who is eligible for Mackay Project can pay senior fare.<br>Foreign senior should pay adult fare.</span>',
	'_page01_008' => "Payment methods:",
	'_page01_009' => "For each Booking code, all or some selected tickets <font style='BACKGROUND-COLOR:YELLOW'><font color=#ff0000>may be paid for via online payment.</font> Any remaining seats will not be reserved.</font>",
	'_page01_009-1' => '<font color=#ff0000>If passenger makes up a round-trip ticket by section way through net (including voice ticketing), (for example, Taipei to Taichung and Taichung to Kaohsiung for one-way then Kaohsiung to Tai-chung and Tai-chung to Taipei for return), passenger can get a special discount but he must make the payment pick up the tickets at the station.</font>',
	'_page01_010' => 'To buy a round-trip ticket, click the Round-Trip Ticket option in the payment website and <span style="color:#F00;">enter your Passport number and Booking code </span>to make a payment after ordering your outbound and Return bround tickets.<br>If you cannot book all of your round-trip tickets at once, <span style="color:#F00;">you can make the payment for one-way tickets instead.</span>',
	'_page01_010-1' => 'After your credit card number has been authorized successfully, <span style="color:#F00;">the ticket information, such as the car number and seat number, will be displayed. <span style="background-color: yellow;">If you cancel the payment, the Booking code will be returned to the ticket booking system for other passengers to book.</span></span>',
	'_page01_011' => '<span style="color:#F00;">The online payment system is available for payment for one day cruise trains.</span>',
	'_page01_012' => "How to pick up your ticket and the deadline:",
	'_page01_013' => 'Take your ID card (Passport or Residence permit or Entry-and-exit-permits,which is used to book) at the “TRA Ticket Counters” ,post office and convenience store (7-ELEVEN, Hi-Life, Family Mart, OK Mart) <span style="color:#F00;">30 minutes before taking the train.</span>',
	'_page01_014' => "When picking up your ticket, present your completed ticket pick-up form and identify yourself as the “Passenger who makes the payment online via credit card.” If you cannot print a ticket pick-up form, go to the Ticket Counters to ask for one and complete it. <font color=#ff0000>(To protect your rights, always bring your completed ticket pick-up form with you when picking up your ticket.)</font>",
	'_page01_015' => "How to cancel online credit card payment and the deadline:",
	'_page01_016' => 'Cancellation should be done up to <span style="color:#F00;">30 minutes</span> before your train departs.',
	'_page01_016a' => "",
	'_page01_017' => "A handling fee will be charged for each ticket that is cancelled.",
	'_page01_018' => 'All purchased tickets with the same Booking code should be cancelled together. To cancel some of the tickets, pick them up at TRA station and refund them <span style="color:#F00;">with the original credit card</span> used to pay.',
	'_page01_018-1' => '',
	'_page01_019' => "Tickets not picked up after payment.",
	'_page01_020' => 'Purchased tickets are kept in a database and cannot be resold. <font color=#ff0000>Whether you pick up your ticket or not, ticket payment will be collected if you do not cancel payment before the deadline.</font>',
	'_page01_021' => "National Travel Card:",
	'_page01_022' => 'For civil servants who want to apply for the “Compulsory Vacation Subsidies,” check the “National Travel Card” option on this payment webpage and select a “Tourist Destination.” ',
	'_page01_023' => 'After booking, if the payment system is busy,please make the payment later <span style="color:#F00;">before the deadline</span>. You do not have to perform all steps at once.',
	'_page01_024' => '<span style="font-weight:bold;">The “VISA , MasterCard, JCB” card from each bank can be used on the system that uses the latest “VISA,MasterCard, JCB” security mechanism.</span>',
	'_page01_025' => '',
	'_page01_026' => 'What do I do if a typhoon arrives on the day I have booked my ticket?',
	'_page01_027' => 'If the train you are scheduled to take is subject to a typhoon sea warning, You can take your tickets to TRA station to get a full refund. If you cancel payment on the Online payment system, A handling fee will be charged for each ticket that is cancelled.',
    '_page01_028' => '<span style="color:#F00;">One booking code can charge only one fee, sometimes credit card issue bank will inform coustomer "Authorization code" when you try to pay, either it is successful or not.You can use (Payment Records Query) to check if your transaction was successful.</span>',
    '_page01_029' => '<span style="color:#00F;">Passengers who make a payment via a digital credit card (virtual one) cannot refund their tickets.Do not use digital credit card as possible.</span>',
    '_page01_030' => 'Other rules are in accordance with the passenger transportation regulations established by the Taiwan Railways Administration.',
    '_page01_031' => '',
);
?>
