<?php
$str = "AI CHENG GUO JI YOU XIAN GONG SI,CAI CHENG GUO JI YOU XIAN GONG SI";
$str = "AI_CHENG_GUO_JI_YOU_XIAN_GONG_SI,CAI_CHENG_GUO_JI_YOU_XIAN_GONG_SI";

echo str_pad($str, 40, '@', STR_PAD_RIGHT) ;
?>